import type { MenuItem, MenuCategory } from '@/types'

export type MenuCategoryEntry = {
  id: MenuCategory
  label: string
  labelNl: string
  shortLabel: string
}

export const categoryLabels: Record<MenuCategory, { label: string; labelNl: string }> = {
  starters: {
    label: 'Indian Starters and Street Food in Den Haag',
    labelNl: 'Indiase Starters en Streetfood in Den Haag',
  },
  soups: {
    label: 'Indian Soups in Den Haag',
    labelNl: 'Indiase Soepen in Den Haag',
  },
  vegan: {
    label: 'Vegan Dishes',
    labelNl: 'Veganistische Gerechten',
  },
  tandoori: {
    label: 'Tandoori - Clay Oven Grill Specialties',
    labelNl: 'Tandoori Gerechten - Specialiteiten uit de Kleistenen Oven',
  },
  'veg-curries': {
    label: 'Vegetarian Indian Curries in Den Haag',
    labelNl: 'Vegetarische Indiase Curries in Den Haag',
  },
  chicken: {
    label: 'Chicken Curries in Den Haag',
    labelNl: 'Kip Curries in Den Haag',
  },
  'lamb-mutton': {
    label: 'Lamb and Mutton Curries in Den Haag',
    labelNl: 'Lam en Schapenvlees Curries in Den Haag',
  },
  'indo-chinese': {
    label: 'Indo-Chinese Dishes in Den Haag',
    labelNl: 'Indo-Chinese Gerechten in Den Haag',
  },
  biryani: {
    label: 'Biryani in Den Haag',
    labelNl: 'Biryani in Den Haag',
  },
  breads: {
    label: 'Indian Breads Baked Fresh in the Tandoor',
    labelNl: 'Indiaas Brood Vers Gebakken in de Tandoor',
  },
  'rice-sides': {
    label: 'Rice, Sides and Thali',
    labelNl: 'Rijst, Bijgerechten en Thali',
  },
  desserts: {
    label: 'Indian Desserts in Den Haag',
    labelNl: 'Indiase Desserts in Den Haag',
  },
  drinks: {
    label: 'Drinks and Lassi in Den Haag',
    labelNl: 'Dranken en Lassi in Den Haag',
  },
}

export const menuCategories: MenuCategoryEntry[] = [
  {
    id: 'starters',
    label: categoryLabels['starters'].label,
    labelNl: categoryLabels['starters'].labelNl,
    shortLabel: 'Starters',
  },
  {
    id: 'soups',
    label: categoryLabels['soups'].label,
    labelNl: categoryLabels['soups'].labelNl,
    shortLabel: 'Soups',
  },
  {
    id: 'vegan',
    label: 'Vegan Dishes',
    labelNl: 'Veganistische Gerechten',
    shortLabel: 'Vegan',
  },
  {
    id: 'tandoori',
    label: categoryLabels['tandoori'].label,
    labelNl: categoryLabels['tandoori'].labelNl,
    shortLabel: 'Tandoori',
  },
  {
    id: 'veg-curries',
    label: categoryLabels['veg-curries'].label,
    labelNl: categoryLabels['veg-curries'].labelNl,
    shortLabel: 'Veg Curries',
  },
  {
    id: 'chicken',
    label: categoryLabels['chicken'].label,
    labelNl: categoryLabels['chicken'].labelNl,
    shortLabel: 'Chicken',
  },
  {
    id: 'lamb-mutton',
    label: categoryLabels['lamb-mutton'].label,
    labelNl: categoryLabels['lamb-mutton'].labelNl,
    shortLabel: 'Lamb & Mutton',
  },
  {
    id: 'indo-chinese',
    label: categoryLabels['indo-chinese'].label,
    labelNl: categoryLabels['indo-chinese'].labelNl,
    shortLabel: 'Indo-Chinese',
  },
  {
    id: 'biryani',
    label: categoryLabels['biryani'].label,
    labelNl: categoryLabels['biryani'].labelNl,
    shortLabel: 'Biryani',
  },
  {
    id: 'breads',
    label: categoryLabels['breads'].label,
    labelNl: categoryLabels['breads'].labelNl,
    shortLabel: 'Breads',
  },
  {
    id: 'rice-sides',
    label: categoryLabels['rice-sides'].label,
    labelNl: categoryLabels['rice-sides'].labelNl,
    shortLabel: 'Rice & Sides',
  },
  {
    id: 'desserts',
    label: categoryLabels['desserts'].label,
    labelNl: categoryLabels['desserts'].labelNl,
    shortLabel: 'Desserts',
  },
  {
    id: 'drinks',
    label: categoryLabels['drinks'].label,
    labelNl: categoryLabels['drinks'].labelNl,
    shortLabel: 'Drinks',
  },
]

export const menuItems: MenuItem[] = [
  // ─── STARTERS ────────────────────────────────────────────────────────────
  {
    id: 'veg-samosa-chaat',
    name: 'Veg Samosa Chaat',
    price: 10,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/samosa-chaat.webp',
    description: 'Crushed samosa with yogurt, chickpeas, mint and tamarind sauce.',
    descriptionNl: 'Verpletterd samosa met yogurt, kikkererwten, munt en tamarindesaus.',
  },
  {
    id: 'pani-puri',
    name: 'Pani Puri',
    price: 8,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/pani-puri.webp',
    description: 'Filled dough balls with potato, chickpeas, mint and tamarind sauce and tangy water.',
    descriptionNl: 'Gevulde deegballen met aardappel, kikkererwten, munt- en tamarindesaus en tangy water.',
  },
  {
    id: 'dahi-puri',
    name: 'Dahi Puri',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dahi-puri.webp',
    description: 'Filled dough balls with potato, chickpeas, mint, tamarind sauce, and yogurt.',
    descriptionNl: 'Gevulde deegballen met aardappel, kikkererwten, munt-, tamarindesaus, en yogurt.',
  },
  {
    id: 'aloo-tikki',
    name: 'Aloo Tikki',
    price: 8,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/aloo-tikki.webp',
    description: 'Potato Cutlet.',
    descriptionNl: 'Aardappel Kotelet.',
  },
  {
    id: 'papdi-chaat',
    name: 'Papdi Chaat',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/papdi-chaat.webp',
    description: 'Flour crisps with potato mix, tamarind and mint sauce.',
    descriptionNl: 'Meelcrisps met aardappelmix, tamarinde- en muntsaus.',
  },
  {
    id: 'mixed-chaat',
    name: 'Mixed Chaat',
    price: 12,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-chaat.jpg',
    description: 'Combo Veg. Samosa (1), Aloo Tikki (1), Papdi (crushed), yogurt and sauce.',
    descriptionNl: 'Combo Veg. Samosa (l), Aloo Tikki (1) Papdi (verpletterd), yogurt en saus.',
  },
  {
    id: 'plain-papad',
    name: 'Plain Papad',
    price: 3.5,
    category: 'starters',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/plain-papad.webp',
    description: 'Crispy lentil cracker.',
    descriptionNl: 'Knapperige linzencracker.',
  },
  {
    id: 'masala-papad',
    name: 'Masala Papad',
    price: 5,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/masala-papad.webp',
    description: 'Papad with spices, onion and tomato.',
    descriptionNl: 'Papad met kruiden, ui en tomaat.',
  },
  {
    id: 'onion-bhaji',
    name: 'Onion Bhaji',
    price: 8,
    category: 'starters',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/onion-bhaji.jpg',
    description: 'Crispy onion fritters served with mint and tamarind sauce.',
    descriptionNl: 'Uienbeignets geserveerd met munt en tamarindesaus.',
  },
  {
    id: 'samosa',
    name: 'Samosa (Veg/Lamb/Chicken)',
    price: 8,
    category: 'starters',
    dietary: ['halal'],
    image: '/images/dishes/veg-samosa.webp',
    description: 'Triangular, golden-fried savory pastry with chickpea filling.',
    descriptionNl: 'Driehoekig, goudgebakken hartig gebakje met kikkererwtenvullingen.',
  },

  // ─── CLAY OVEN TANDOORI ──────────────────────────────────────────────────
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-tikka.webp',
    description: 'Cubes of Indian cheese grilled with onions and bell peppers.',
    descriptionNl: 'Blokjes Indiase kaas gegrild met uien en paprika.',
  },
  {
    id: 'malai-soya-chaap',
    name: 'Malai Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-soya-chap.jpg',
    description: 'Soya chunks marinated in yogurt.',
    descriptionNl: 'Sojablokjes gemarineerd in yoghurt.',
  },
  {
    id: 'achari-soya-chaap',
    name: 'Achari Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/soya-chaap-achari.jpg',
    description: 'Soya chunks marinated in Indian pickling sauce.',
    descriptionNl: 'Sojablokjes gemarineerd in Indiase augurkensaus.',
  },
  {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-chicken.webp',
    description: 'Grilled chicken marinated in Indian spices.',
    descriptionNl: 'Gegrilde kip gemarineerd in Indiase kruiden.',
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka.webp',
    description: 'Grilled chicken breast marinated in Indian spices.',
    descriptionNl: 'Gegrilde kipfilet gemarineerd in Indiase kruiden.',
  },
  {
    id: 'chicken-malai-tikka',
    name: 'Chicken Malai Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-malai-tikka.webp',
    description: 'Grilled chicken breast marinated in cream.',
    descriptionNl: 'Gegrilde kipfilet gemarineerd in room.',
  },
  {
    id: 'chicken-hariyali-tikka',
    name: 'Chicken Hariyali Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-hariyali-tikka.jpg',
    description: 'Grilled chicken breast marinated in yogurt and spinach.',
    descriptionNl: 'Gegrilde kipfilet gemarineerd in yoghurt en spinazie.',
  },
  {
    id: 'chicken-lasooni-tikka',
    name: 'Chicken Lasooni Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-lasooni-tikka.webp',
    description: 'Grilled chicken breast marinated in garlic and spices.',
    descriptionNl: 'Gegrilde kipfilet gemarineerd in knoflook en kruiden.',
  },
  {
    id: 'lamb-seekh-kebab',
    name: 'Lamb Seekh Kebab',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-kebab.webp',
    description: 'Spiced minced lamb skewer.',
    descriptionNl: 'Gekruid lamsgehakt spies.',
  },
  {
    id: 'tandoori-prawn-fish',
    name: 'Tandoori Prawn/Fish',
    price: 24.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-prawns.webp',
    description: 'Grilled prawns/fish marinated in Indian spices.',
    descriptionNl: 'Gegrilde garnalen/vis gemarineerd in Indiase kruiden.',
  },
  {
    id: 'chicken-seekh-kebab',
    name: 'Chicken Seekh Kebab',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-seekh-kebab.jpg',
    description: 'Spiced minced chicken skewer.',
    descriptionNl: 'Gekruid kipgehakt spies.',
  },
  {
    id: 'chopras-non-veg-platter',
    name: 'Chopras Non Veg Platter',
    price: 30,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chopras-non-veg-platter.webp',
    description: 'Mix of various clay oven meats (without fish and prawns).',
    descriptionNl: 'Mix van diverse vlees kleioven (zonder vis en garnalen).',
  },

  // ─── SOUP ────────────────────────────────────────────────────────────────
  {
    id: 'chicken-soup',
    name: 'Chicken Soup',
    price: 8.5,
    category: 'soups',
    dietary: ['halal'],
    image: '/images/dishes/chicken-soup.webp',
    description: 'Soup made with chicken.',
    descriptionNl: 'Soep gemaakt met kip.',
  },
  {
    id: 'tomato-soup',
    name: 'Tomato Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/tomato-soup.webp',
    description: 'Soup made with tomatoes.',
    descriptionNl: 'Soep gemaakt met tomaten.',
  },
  {
    id: 'veg-manchow-soup',
    name: 'Veg Manchow Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/manchow-soup.webp',
    description: 'Soup with vegetables, noodles and Asian spices.',
    descriptionNl: 'Soep met groenten, noedels en Aziatische kruiden.',
  },
  {
    id: 'lentil-soup',
    name: 'Lentil Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/dal-soup.webp',
    description: 'Soup made with lentils.',
    descriptionNl: 'Soep gemaakt met linzen.',
  },

  // ─── VEG CURRIES ─────────────────────────────────────────────────────────
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    price: 18.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-makhani.webp',
    description: 'Black lentil curry with cream.',
    descriptionNl: 'Zwarte linzencurry met room.',
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    price: 16,
    category: 'veg-curries',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/dal-tadka.webp',
    description: 'Yellow lentil curry with Indian spices.',
    descriptionNl: 'Geel linzencurry met Indiase specerijen.',
  },
  {
    id: 'chana-masala',
    name: 'Chana Masala',
    price: 15,
    category: 'veg-curries',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/channa-masala.webp',
    description: 'Chickpea curry, cumin, ginger, coriander.',
    descriptionNl: 'Kikkererwten curry, komijn, gember, koriander.',
  },
  {
    id: 'rajma-raseela',
    name: 'Rajma Raseela',
    price: 15,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/rajma-masala.webp',
    description: 'Kidney beans in tomato sauce.',
    descriptionNl: 'Kidney bonen in tomatensaus.',
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    price: 14,
    category: 'veg-curries',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/aloo-gobhi.webp',
    description: 'Potato and cauliflower.',
    descriptionNl: 'Aardappel en bloemkool.',
  },
  {
    id: 'aloo-jeera',
    name: 'Aloo Jeera',
    price: 12.5,
    category: 'veg-curries',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/aloo-jeera.webp',
    description: 'Potato with cumin.',
    descriptionNl: 'Aardappel met komijn.',
  },
  {
    id: 'mixed-veg',
    name: 'Mixed Veg',
    price: 15,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mixed-veg.webp',
    description: 'Corn, carrot, green beans, bell pepper, peas, Indian cheese.',
    descriptionNl: 'Maïs, wortel, sperziebonen, paprika, erwten, Indiase kaas.',
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    price: 14,
    category: 'veg-curries',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/bhandi-masala.jpg',
    description: 'Okra with onion and tomato.',
    descriptionNl: 'Oker met ui en tomaat.',
  },
  {
    id: 'baingan-bharta',
    name: 'Baingan Bharta',
    price: 14,
    category: 'veg-curries',
    dietary: ['veg', 'halal', 'glutenFree'],
    image: '/images/dishes/baingan-bharta.webp',
    description: 'Eggplant with onion, tomato, coriander.',
    descriptionNl: 'Aubergine met ui, tomaat, koriander.',
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    price: 18.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kofta.webp',
    description: 'Fried balls filled with potato, Indian cheese in cashew nut sauce.',
    descriptionNl: 'Gebakken balletjes gevuld met aardappel, Indiase kaas in cashewnootsaus.',
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/palak-paneer.webp',
    description: 'Indian cheese in creamy spinach sauce.',
    descriptionNl: 'Indiase kaas in romige spinaziesaus.',
  },
  {
    id: 'karahi-paneer',
    name: 'Karahi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/karahi-paneer.webp',
    description: 'Indian cheese with bell pepper, onion and tomato cooked in thick sauce.',
    descriptionNl: 'Indiase kaas met paprika, ui en tomaat gekookt in dikke saus.',
  },
  {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/shahi-paneer.webp',
    description: 'Indian cheese in sweet and sour creamy sauce with tomato and cashew nuts.',
    descriptionNl: 'Indiase kaas in zoetzure romige saus met tomaat en cashewnoten.',
  },
  {
    id: 'handi-paneer',
    name: 'Handi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/handi-paneer.webp',
    description: 'Indian cheese in creamy sauce with tomato, cashew nuts and onion.',
    descriptionNl: 'Indiase kaas in romige saus met tomaat, cashewnoten en ui.',
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-butter-masala.webp',
    description: 'Indian cheese in creamy sauce with butter, tomato, onion and cashew nuts.',
    descriptionNl: 'Indiase kaas in romige saus met boter, tomaat, ui en cashewnoten.',
  },
  {
    id: 'tawa-paneer-masala',
    name: 'Tawa Paneer Masala',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tawa-paneer.webp',
    description: 'Indian cheese with diced tomatoes in sauce with tomato and onion.',
    descriptionNl: 'Indiase kaas met tomatenblokjes in saus met tomaat en ui.',
  },
  {
    id: 'chopras-special-paneer',
    name: 'Chopras Special Paneer',
    price: 20,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chopras-special-paneer.webp',
    description: 'Cooked Indian cheese (surprise dish).',
    descriptionNl: 'Gekookte Indiase kaas (verrassingsgerecht).',
  },

  // ─── CHICKEN CURRIES ─────────────────────────────────────────────────────
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    price: 20,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/butter-chicken.webp',
    description: 'Chicken in creamy sauce with tomato and cashew nuts.',
    descriptionNl: 'Kip in romige saus met tomaat en cashewnoten.',
  },
  {
    id: 'karahi-chicken',
    name: 'Karahi Chicken',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/kadai-chicken.jpg',
    description: 'Chicken with bell pepper, onion and tomato cooked in thick sauce.',
    descriptionNl: 'Kip met paprika, ui en tomaat gekookt in dikke saus.',
  },
  {
    id: 'chicken-handi',
    name: 'Chicken Handi',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-handi.webp',
    description: 'Chicken in creamy sauce with tomato, cashew nuts and onion.',
    descriptionNl: 'Kip in romige saus met tomaat, cashewnoten en ui.',
  },
  {
    id: 'chicken-vindaloo',
    name: 'Chicken Vindaloo',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-vindaloo.jpg',
    description: 'Chicken with potato in spicy sauce.',
    descriptionNl: 'Kip met aardappel in pittige saus.',
  },
  {
    id: 'chicken-methi-malai',
    name: 'Chicken Methi Malai',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-methi-malai.webp',
    description: 'Chicken in creamy fenugreek sauce.',
    descriptionNl: 'Kip in romige fenegriek saus.',
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-curry.webp',
    description: 'Chicken in sauce with Indian spices.',
    descriptionNl: 'Kip in saus met lndiase specerijen.',
  },
  {
    id: 'chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    price: 20,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-masala.jpg',
    description: 'Chicken breast in creamy sauce with butter, tomato, onion and cashew nuts.',
    descriptionNl: 'Kipfilet in romige saus met boter, tomaat, ui en cashewnoten.',
  },

  // ─── LAMB CURRIES ────────────────────────────────────────────────────────
  {
    id: 'mutton-rogan-josh',
    name: 'Mutton Rogan Josh',
    price: 22.5,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-rogan-josh.webp',
    description: 'Lamb in spicy sauce.',
    descriptionNl: 'Lams in pittige saus.',
  },
  {
    id: 'mutton-vindaloo',
    name: 'Mutton Vindaloo',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-vindaloo.jpg',
    description: 'Lamb with potato in spicy sauce.',
    descriptionNl: 'Lams met aardappel in pittige saus.',
  },
  {
    id: 'mutton-korma',
    name: 'Mutton Korma',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-korma.webp',
    description: 'Lamb in creamy tomato sauce.',
    descriptionNl: 'Lams in romige tomatensaus.',
  },
  {
    id: 'mutton-handi',
    name: 'Mutton Handi',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/handi-mutton.webp',
    description: 'Lamb in creamy sauce with tomato, cashew nuts and onion.',
    descriptionNl: 'Lams in romige saus met tomaat, cashewnoten en ui.',
  },
  {
    id: 'rara-gosht',
    name: 'Rara Gosht',
    price: 25,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/rara-gosht.webp',
    description: 'Minced lamb with lamb fillet cooked in Indian spices.',
    descriptionNl: 'Lamsgehakt met lamsfilet gebakken in Indiase kruiden.',
  },
  {
    id: 'keema-saag',
    name: 'Keema Saag',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/keema-saag.jpg',
    description: 'Minced lamb cooked with spinach and tomato.',
    descriptionNl: 'Lamsgehakt gebakken met spinazie en tomaat.',
  },
  {
    id: 'tawa-mutton-masala',
    name: 'Tawa Mutton Masala',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/tawa-mutton-masala.webp',
    description: 'Indian cheese with diced tomatoes in sauce with tomato and onion.',
    descriptionNl: 'Indiase kaas met tomatenblokjes in saus met tomaat en ui.',
  },
  {
    id: 'mutton-karahi',
    name: 'Mutton Karahi',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-karahi.webp',
    description: 'Lamb with bell pepper, onion and tomato cooked in thick sauce.',
    descriptionNl: 'Lams met paprika, ui en tomaat gekookt in dikke saus.',
  },

  // ─── INDIAN CHINESE ──────────────────────────────────────────────────────
  {
    id: 'chicken-spring-roll',
    name: 'Chicken Spring Roll',
    price: 11,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chicken-spring-roll.jpg',
    description: 'Chicken spring roll.',
    descriptionNl: 'Kip loempia.',
  },
  {
    id: 'chilli-chicken',
    name: 'Chilli Chicken',
    price: 20,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chilli-chicken.jpg',
    description: 'Crispy chicken in spicy sauce.',
    descriptionNl: 'Crispy kip in pittige saus.',
  },
  {
    id: 'veg-spring-roll',
    name: 'Veg Spring Roll',
    price: 10,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-spring-roll.jpg',
    description: 'Vegetarian spring roll.',
    descriptionNl: 'Vegetarische loempia.',
  },
  {
    id: 'chilli-paneer',
    name: 'Chilli Paneer',
    price: 18,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chilli-paneer.webp',
    description: 'Indian cheese in spicy sauce.',
    descriptionNl: 'Indiase kaas in pittige saus.',
  },
  {
    id: 'veg-noodles',
    name: 'Veg Noodles',
    price: 14.5,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-noodles.jpg',
    description: 'Vegetarian noodles.',
    descriptionNl: 'Vegetarische bami.',
  },

  // ─── THALI ───────────────────────────────────────────────────────────────
  {
    id: 'veg-thali',
    name: 'Veg Thali',
    price: 30,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-thali.jpg',
    description: 'Platter with various vegetarian dishes.',
    descriptionNl: 'Schotel met diverse vegetarische gerechten.',
  },
  {
    id: 'non-veg-thali',
    name: 'Chopra\'s Special Non Veg Thali',
    price: 35,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/non-veg-thali.jpg',
    description: 'Platter with various vegetarian and meat dishes.',
    descriptionNl: 'Schotel met diverse vegetarische en vlees gerechten.',
  },

  // ─── BIRYANI & RICE ──────────────────────────────────────────────────────
  {
    id: 'prawn-biryani',
    name: 'Prawn Biryani',
    price: 23,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/prawns-biryani.jpg',
    description: 'Prawns cooked with rice.',
    descriptionNl: 'Garnalen gekookt met rijst.',
  },
  {
    id: 'lamb-biryani',
    name: 'Lamb Biryani',
    price: 22,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/muton-biryani.webp',
    description: 'Lamb cooked with rice.',
    descriptionNl: 'Lam gekookt met rijst.',
  },
  {
    id: 'veg-biryani',
    name: 'Veg Biryani',
    price: 15,
    category: 'biryani',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/veg-biryani.jpg',
    description: 'Rice with spices and vegetables.',
    descriptionNl: 'Rijst met kruiden en groenten.',
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    price: 19,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/chicken-biryani.webp',
    description: 'Chicken cooked with rice.',
    descriptionNl: 'Kip gekookt met rijst.',
  },
  {
    id: 'steamed-rice',
    name: 'Steamed Rice',
    price: 7.5,
    category: 'rice-sides',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/steamed-rice.webp',
    description: 'Steamed rice.',
    descriptionNl: 'Gestoomde rijst.',
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    price: 10,
    category: 'rice-sides',
    dietary: ['vegan', 'halal', 'glutenFree'],
    image: '/images/dishes/jeera-rice.jpg',
    description: 'Rice with cumin.',
    descriptionNl: 'Rijst met komijn.',
  },
  {
    id: 'veg-fried-rice',
    name: 'Veg Fried Rice',
    price: 14,
    category: 'rice-sides',
    dietary: ['veg', 'halal', 'glutenFree'],
    image: '/images/dishes/veg-fried-rice.webp',
    description: 'Stir-fried rice with various vegetables.',
    descriptionNl: 'Roergebakken rijst met diverse groenten.',
  },
  {
    id: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    price: 18,
    category: 'rice-sides',
    dietary: ['halal', 'glutenFree'],
    image: '/images/dishes/chicken-fried-rice.jpg',
    description: 'Stir-fried rice with chicken.',
    descriptionNl: 'Roergebakken rijst met kip.',
  },

  // ─── BREADS ──────────────────────────────────────────────────────────────
  {
    id: 'pudina-paratha',
    name: 'Pudina Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mint-paratha.jpg',
    description: 'Whole wheat flatbread with mint leaves, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood met muntblaadjes, gebakken in kleioven.',
  },
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-paratha.jpg',
    description: 'Whole wheat flatbread with potato, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood met aardappel, gebakken in kleioven.',
  },
  {
    id: 'missi-roti',
    name: 'Missi Roti',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/missi-roti.jpg',
    description: 'Whole wheat and chickpea flour flatbread with spices, baked in clay oven.',
    descriptionNl: 'Volkoren en kikkererwtenmeel platbrood met kruiden, gebakken in kleioven.',
  },
  {
    id: 'lachha-paratha',
    name: 'Lachha Paratha',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/laccha-paratha.jpg',
    description: 'Layered whole wheat flatbread baked in clay oven.',
    descriptionNl: 'Gelaagd volkoren platbrood gebakken in kleioven.',
  },
  {
    id: 'onion-roti',
    name: 'Onion Tandoori Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/onion-tandoori-roti.jpg',
    description: 'Whole wheat flatbread with onions, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood met uien, gebakken in kleioven.',
  },
  {
    id: 'garlic-roti',
    name: 'Garlic Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-roti.jpg',
    description: 'Whole wheat flatbread with garlic, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood met knoflook, gebakken in kleioven.',
  },
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    price: 3,
    category: 'breads',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/tandoori-roti.jpg',
    description: 'Whole wheat flatbread, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood, gebakken in kleioven.',
  },
  {
    id: 'butter-roti',
    name: 'Tandoori Butter Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tandoori-butter-roti.jpg',
    description: 'Whole wheat flatbread with butter, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood met boter, gebakken in kleioven.',
  },
  {
    id: 'paneer-paratha',
    name: 'Paneer Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-paratha.jpg',
    description: 'Whole wheat flatbread with Indian cheese, baked in clay oven.',
    descriptionNl: 'Volkoren platbrood met Indiase kaas, gebakken in kleioven.',
  },
  {
    id: 'cheese-naan',
    name: 'Cheese Naan',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cheese-naan.webp',
    description: 'White wheat flour flatbread with Dutch cheese, baked in clay oven.',
    descriptionNl: 'Platbrood van wit tarwemeel met Nederlandse kaas, gebakken in kleioven.',
  },
  {
    id: 'keema-naan',
    name: 'Keema Naan',
    price: 7,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/keema-naan.jpg',
    description: 'White wheat flour flatbread with minced lamb or chicken, baked in clay oven.',
    descriptionNl: 'Platbrood van wit tarwemeel met lams- of kipgehakt, gebakken in kleioven.',
  },
  {
    id: 'garlic-naan',
    name: 'Garlic Naan',
    price: 4.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-naan.webp',
    description: 'White wheat flour flatbread with garlic, baked in clay oven.',
    descriptionNl: 'Platbrood van wit tarwemeel met knoflook, gebakken in kleioven.',
  },
  {
    id: 'paneer-naan',
    name: 'Paneer Naan',
    price: 6,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-naan.jpg',
    description: 'White wheat flour flatbread with Indian cheese, baked in clay oven.',
    descriptionNl: 'Platbrood van wit tarwemeel met Indiase kaas, gebakken in kleioven.',
  },
  {
    id: 'plain-naan',
    name: 'Plain Naan',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-naan.jpg',
    description: 'White wheat flour flatbread, baked in clay oven.',
    descriptionNl: 'Platbrood van wit tarwemeel, gebakken in kleioven.',
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/butter-naan.webp',
    description: 'White wheat flour flatbread with butter, baked in clay oven.',
    descriptionNl: 'Platbrood van wit tarwemeel met boter, gebakken in kleioven.',
  },

  // ─── ROLLS ───────────────────────────────────────────────────────────────
  {
    id: 'egg-kathi-roll',
    name: 'Egg Kathi Roll',
    price: 12,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/egg-roll.jpg',
    description: 'Wrap filled with omelet, spices and fresh salad.',
    descriptionNl: 'Wrap gevuld met omelet, kruiden en verse salade.',
  },
  {
    id: 'mutton-seekh-roll',
    name: 'Mutton Seekh Roll',
    price: 16,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-roll.jpg',
    description: 'Wrap filled with lamb meat and fresh salad.',
    descriptionNl: 'Wrap gevuld met lamsvlees en verse salade.',
  },
  {
    id: 'chicken-tikka-roll',
    name: 'Chicken Tikka Roll',
    price: 14,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-roll.jpg',
    description: 'Wrap filled with grilled chicken breast and fresh salad.',
    descriptionNl: 'Wrap gevuld met gegrilde kipfilet en verse salade.',
  },
  {
    id: 'paneer-roll',
    name: 'Paneer Roll',
    price: 12,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-roll.jpg',
    description: 'Wrap filled with seasoned Indian cheese and fresh salad.',
    descriptionNl: 'Wrap gevuld met gekruide Indiase kaas en verse salade.',
  },

  // ─── KIDS DELIGHT ────────────────────────────────────────────────────────
  {
    id: 'fries-nuggets',
    name: 'Fries & Nuggets',
    price: 8,
    category: 'rice-sides',
    dietary: ['halal', 'glutenFree'],
    image: '/images/dishes/fries-chicken-nuggets-kids.jpg',
    description: 'Fries, chicken nuggets and cucumber.',
    descriptionNl: 'Frietjes, kipnuggets en komkommer.',
  },

  // ─── SIDE PLATES ─────────────────────────────────────────────────────────
  {
    id: 'boondi-raita',
    name: 'Boondi Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/boondi-raita.webp',
    description: 'Yogurt with fried chickpea pearls.',
    descriptionNl: 'Yogurt met gefrituurde kikkererwtenbolletjes.',
  },
  {
    id: 'cucumber-raita',
    name: 'Cucumber Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cucumber-raita.webp',
    description: 'Yogurt with cucumber.',
    descriptionNl: 'Yogurt met komkommer.',
  },
  {
    id: 'mixed-raita',
    name: 'Mixed Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-raita.webp',
    description: 'Yogurt with cucumber and fried chickpea pearls.',
    descriptionNl: 'Yogurt met komkommer en gefrituurde kikkererwtenbolletjes.',
  },
  {
    id: 'green-chillies',
    name: 'Green Chillies',
    price: 2,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/green-chilli.webp',
    description: 'Fresh green chilies (5 pcs).',
    descriptionNl: 'Verse groene pepers (5 pcs).',
  },
  {
    id: 'onion-salad',
    name: 'Onion Salad',
    price: 5,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/onion-salad.jpg',
    description: 'Fresh onion.',
    descriptionNl: 'Verse ui.',
  },
  {
    id: 'mixed-salad',
    name: 'Mixed Salad',
    price: 5,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mixed-salad.jpg',
    description: 'Fresh onion, cucumber, tomato, carrot.',
    descriptionNl: 'Verse ui, komkommer, tomaat, wortel.',
  },
  {
    id: 'mixed-pickle',
    name: 'Mixed Pickle',
    price: 3,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mixed-pickle.webp',
    description: 'Spicy marinade of fruit and vegetables in spices and oil.',
    descriptionNl: 'Pittige marinade van fruit en groenten in specerijen en olie.',
  },
  {
    id: 'mint-chutney',
    name: 'Mint Chutney',
    price: 2,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mint-chutney.png',
    description: 'Fresh sauce made of mint, coriander, spinach, green chili, gember, garlic, lemon, yogurt and Indian spices.',
    descriptionNl: 'Verse saus gemaakt van munt, koriander, spinazie, groene chili, gember, knoflook, citroen, yoghurt en Indiase kruiden.',
  },
  {
    id: 'tamarind-chutney',
    name: 'Tamarind Chutney',
    price: 2,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/tamarind-chutney.png',
    description: 'Fresh tamarind sauce with jaggery, sugar, Indian spices, cumin and dried ginger powder, for a sweet and sour taste.',
    descriptionNl: 'Verse tamarindesaus met jaggery, suiker, Indiase kruiden, komijn en gedroogd gemberpoeder, voor een zoetzure smaak.',
  },
  {
    id: 'vinegar-onion',
    name: 'Vinegar Onion',
    price: 2,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/vinegar-onion.png',
    description: 'Shredded onion in vinegar with sugar and beetroot, for a sweet and sour taste.',
    descriptionNl: 'Gesnipperde ui in azijn met suiker en rode biet, voor een zoetzure smaak.',
  },

  // ─── DESSERTS ────────────────────────────────────────────────────────────
  {
    id: 'moong-dal-halwa',
    name: 'Moong Dal Halwa',
    price: 8,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/moong-dal-halwa.webp',
    description: 'Sweet lentil pudding.',
    descriptionNl: 'Zoete linzenpudding.',
  },
  {
    id: 'saffron-kheer',
    name: 'Saffron Kheer',
    price: 5.5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/saffron-kheer.webp',
    description: 'Rice pudding with saffron.',
    descriptionNl: 'Rijstpudding met saffraan.',
  },
  {
    id: 'kulfi-pistachio',
    name: 'Kulfi Pistachio',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/pista-kulfi.webp',
    description: 'Indian ice cream on a stick - pistachio flavor.',
    descriptionNl: 'Indiaas ijs met stokje - pistachemaak.',
  },
  {
    id: 'kulfi-malai',
    name: 'Kulfi Malai',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kulfi.webp',
    description: 'Indian ice cream on a stick - milk cream flavor.',
    descriptionNl: 'Indiaas ijs met stokje - melkroomsmaak.',
  },
  {
    id: 'kulfi-coconut',
    name: 'Kulfi Coconut',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/coconut-kulfi.webp',
    description: 'Indian ice cream on a stick - coconut flavor.',
    descriptionNl: 'Indiaas ijs met stokje - kokossmaak.',
  },
  {
    id: 'kulfi-mango',
    name: 'Kulfi Mango',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-kulfi.webp',
    description: 'Indian ice cream on a stick - mango flavor.',
    descriptionNl: 'Indiaas ijs met stokje - mangosmaak.',
  },
  {
    id: 'rasmalai',
    name: 'Rasmalai',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/rasmalai.webp',
    description: 'Indian cheese balls in sweet saffron milk.',
    descriptionNl: 'Indiase kaas bolletjes in zoete saffraan melk.',
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/gulab-jamun.webp',
    description: 'Fried dough balls in rose water syrup (2 pcs).',
    descriptionNl: 'Gebakken deegballetjes in rozenwatersiroop (2 pcs).',
  },
  {
    id: 'ice-cream-vanilla',
    name: 'Ice Cream Vanilla',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/ice-cream-vanilla.png',
    description: 'Ice cream - vanilla flavor.',
    descriptionNl: 'Ijs - vanillesmaak.',
  },
  {
    id: 'ice-cream-chocolate',
    name: 'Ice Cream Chocolate',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/ice-cream-chocolate.png',
    description: 'Ice cream - chocolate flavor.',
    descriptionNl: 'Ijs - chocoladesmaak.',
  },
  {
    id: 'ice-cream-strawberry',
    name: 'Ice Cream Strawberry',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/ice-cream-strawberry.png',
    description: 'Ice cream - strawberry flavor.',
    descriptionNl: 'Ijs - aardbeiensmaak.',
  },

  // ─── INDIAN DRINKS ───────────────────────────────────────────────────────
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    price: 6,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-lassi.webp',
    description: 'Yogurt mixed with mango pulp.',
    descriptionNl: 'Yoghurt gemengd met mangopulp.',
    isDrink: true,
  },
  {
    id: 'salted-lassi',
    name: 'Salted Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/salted-lassi.webp',
    description: 'Yogurt mixed with salt.',
    descriptionNl: 'Yoghurt gemengd met zout.',
    isDrink: true,
  },
  {
    id: 'masala-tea',
    name: 'Masala Tea',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/indian-masala-tea.jpg',
    description: 'Traditional Indian tea with black tea, milk and spices.',
    descriptionNl: 'Traditionele Indiase thee met zwarte thee, melk en kruiden.',
    isDrink: true,
  },
  {
    id: 'jal-jeera',
    name: 'Jal Jeera',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/jal-jeera.webp',
    description: 'Sweet and sour spiced water with cumin, mint, lemon and black salt.',
    descriptionNl: 'Zoetzuur kruidwater met komijn, munt, citroen en zwart zout.',
    isDrink: true,
  },
  {
    id: 'masala-soda',
    name: 'Masala Soda',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/masala-soda.webp',
    description: 'Soda with added Indian spices and citroen.',
    descriptionNl: 'Soda met toegevoegde Indiase specerijen en citroen.',
    isDrink: true,
  },
  {
    id: 'masala-coke',
    name: 'Masala Coke',
    price: 4,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/masala-coke.webp',
    description: 'Coca-Cola with added Indian spices.',
    descriptionNl: 'Coca-Cola met toegevoegde Indiase specerijen.',
    isDrink: true,
  },
  {
    id: 'sweet-lassi',
    name: 'Sweet Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/sweet-lassi.webp',
    description: 'Yogurt mixed with sugar.',
    descriptionNl: 'Yoghurt gemengd met suiker.',
    isDrink: true,
  },
  {
    id: 'shikanji',
    name: 'Shikanji',
    price: 4.5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/shikanji.webp',
    description: 'Indian drink with water, lemon, salt, sugar and spices.',
    descriptionNl: 'Indiase drank met water, citroen, zout, suiker en specerijen.',
    isDrink: true,
  },
  {
    id: 'thums-up',
    name: 'Thums Up',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/Thumps-Up-Den-Haag.avif',
    description: 'Indian soft drink like Coca-Cola, more fizzy.',
    descriptionNl: 'Indiase frisdrank zoals Coca-Cola, meer bruisend.',
    isDrink: true,
  },
  {
    id: 'limca',
    name: 'Limca',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/Limca-Den-Haag.webp',
    description: 'Indian soft drink with lemon-lime flavor.',
    descriptionNl: 'Indiase frisdrank met citroenlimoensmaak.',
    isDrink: true,
  },
  {
    id: 'maaza',
    name: 'Maaza',
    price: 4,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/Maaza-Deg-haag-1.jpg',
    description: 'Mango Juice.',
    descriptionNl: 'Mango Sap.',
    isDrink: true,
  },

  // ─── OTHER DRINKS ────────────────────────────────────────────────────────
  {
    id: 'apple-juice',
    name: 'Apple Juice',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/apple-juice.png',
    description: 'Homemade apple juice.',
    descriptionNl: 'Homemade APPLE JUICE.',
    isDrink: true,
  },
  {
    id: 'chocolate-milk',
    name: 'Chocolate Milk',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Chocolate-Milk-Den-Haag.jpg',
    description: 'Chocolate milk.',
    descriptionNl: 'CHOCOLATEMILK.',
    isDrink: true,
  },
  {
    id: 'cola-cola-zero',
    name: 'Cola / Cola Zero',
    price: 3.5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/coke-den-haag-scaled.webp',
    description: 'Coca-Cola or Cola Zero.',
    descriptionNl: 'COLA/COLA-ZERO.',
    isDrink: true,
  },
  {
    id: 'fanta',
    name: 'Fanta',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Fanta-Den-Haag.png',
    description: 'Fanta.',
    descriptionNl: 'FANTA.',
    isDrink: true,
  },
  {
    id: 'heineken-00',
    name: 'Heineken 0.0',
    price: 4.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/heineken-zero-Den-HAag.webp',
    description: 'Heineken 0.0%.',
    descriptionNl: 'HEINEKEN 0.0%.',
    isDrink: true,
  },
  {
    id: 'virgin-mojito',
    name: 'Virgin Mojito',
    price: 6.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/virgin-mojito.png',
    description: 'Virgin mojito.',
    descriptionNl: 'VIRGINMOJITO.',
    isDrink: true,
  },
  {
    id: 'orange-juice',
    name: 'Orange Juice',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Orange-Juice-Den-Haag.jpg',
    description: 'Orange juice.',
    descriptionNl: 'ORANGE JUICE.',
    isDrink: true,
  },
  {
    id: 'sprite',
    name: 'Sprite',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Sprite-Den-Haag.jpg',
    description: 'Sprite.',
    descriptionNl: 'SPRITE.',
    isDrink: true,
  },
  {
    id: 'fernandes',
    name: 'Fernandes',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Fernandes-Den-Haag.jpg',
    description: 'Fernandes (Yellow/Green/Orange).',
    descriptionNl: 'FERNANDES (Yellow/Green/Orange).',
    isDrink: true,
  },
  {
    id: 'redbull',
    name: 'RedBull',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/redbull.jpg',
    description: 'RedBull.',
    descriptionNl: 'REDBULL.',
    isDrink: true,
  },
  {
    id: 'coffee-cappuccino',
    name: 'Coffee/Cappuccino',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cappuccino.webp',
    description: 'Coffee or Cappuccino.',
    descriptionNl: 'COFFEE / CAPPUCCINO.',
    isDrink: true,
  },
  {
    id: 'still-water-15l',
    name: 'Still Water 1.5L',
    price: 6,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Still-Water-Den-Haag.jpg',
    description: 'Still water 1.5 litre.',
    descriptionNl: 'STILLWATER 1.5 litre.',
    isDrink: true,
  },
  {
    id: 'sparkling-water-250ml',
    name: 'Sparkling Water 250ml',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Sparkling-Water-Den-Haag.png',
    description: 'Sparkling water 250ml.',
    descriptionNl: 'SPARKLINGWATER 250ml.',
    isDrink: true,
  },
  {
    id: 'ice-tea-peach',
    name: 'Ice Tea Peach',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Iced-Tea-Peach.webp',
    description: 'Ice tea peach.',
    descriptionNl: 'ICE TEAPEACH.',
    isDrink: true,
  },
  {
    id: 'green-tea',
    name: 'Green Tea',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/green-tea.png',
    description: 'Green tea.',
    descriptionNl: 'GREENTEA.',
    isDrink: true,
  },
  {
    id: 'still-water-250ml',
    name: 'Still Water 250ml',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Still-Water-Den-Haag.jpg',
    description: 'Still water 250ml.',
    descriptionNl: 'STILLWATER 250ml.',
    isDrink: true,
  },
  {
    id: 'iced-coffee',
    name: 'Iced Coffee',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/iced-coffee.png',
    description: 'Iced coffee.',
    descriptionNl: 'ICED COFFEE.',
    isDrink: true,
  },
  {
    id: 'ginger-ale',
    name: 'Ginger Ale',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Ginger-Ale-Den-Haag.png',
    description: 'Ginger ale.',
    descriptionNl: 'GINGERALE.',
    isDrink: true,
  },
]